name: Functional tests
on:
  push:
    branches-ignore:
      - 'main'
jobs:
  cypress-run:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cypress functional tests
        uses: cypress-io/github-action@v2
        with:
          build: npm run createQaBundle
          start: npm run serve-build
          config: baseUrl=http://localhost:5000
          wait-on: 'http://localhost:5000'
