name: build-main
on:
  push:
    branches:
      - 'main'
jobs:
  compile_check:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "10.x"
      - name: "NPM install"
        run: npm install
      - name: "Bundle app"
        run: npm run build
